name: Setup
description: Setup environment and install dependencies
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
    - run: npm ci
      shell: bash
